version: '3.8'
services: 

  nginx:
    depends_on:
      - auth_api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "80:80"

  client:
    restart: always
    build: ./newit_ui

  auth_api:
    restart: always
    build: ./Authentication
  
  mongo_db:
    image: mongo:latest
    volumes:
      - /data/db

